package com.nephtysorg.model.pojo;
// Generated 20 avr. 2015 10:17:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable, java.lang.Comparable {


     private Integer id;
     private User user;
     @Size(min=5, max=20)
     private String name;
     @Size(max=100)
     private String description;
     private Set userGroups = new HashSet(0);

    public Group() {
    }

	
    public Group(User user, String name) {
        this.user = user;
        this.name = name;
    }
    public Group(User user, String name, String description, Set userGroups) {
       this.user = user;
       this.name = name;
       this.description = description;
       this.userGroups = userGroups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set userGroups) {
        this.userGroups = userGroups;
    }
    
    @Transient
    public int getSubscriptionNumber() {
        int result = 0;
        Set<UserGroup> temp;
        temp = new HashSet<>(this.userGroups);
        
        for(UserGroup tmp : temp){
            if(tmp.getSubscribed() == (byte)1){
                result ++;
            }
        }
        temp.clear();
        return result;
    }
    
    @Transient
    public int getMembersNumber() {
        int result = 0;
        Set<UserGroup> temp;
        temp = new HashSet<>(this.userGroups);
        
        for(UserGroup tmp : temp){
            if(tmp.getSubscribed()+tmp.getInvited()== (byte)0){
                result ++;
            }
        }
        temp.clear();
        return result;
    }

    @Override
    public int compareTo(Object t) {
        Group g = (Group) t;
        return this.getName().compareTo((g.getName()));         
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.name);
        return hash;
    }
    
     @Override
    public boolean equals(Object t) {
        Group g = (Group) t;
        return this.getName().equals(g.getName());
    }

     @Override
    public String toString (){
        String result = "";
        result+= "Id:"+this.getId()+", Name:"+this.getName()+", Description:"+this.getDescription();
        return result;
    }

}


