package com.nephtysorg.model.pojo;
// Generated 20 avr. 2015 10:17:30 by Hibernate Tools 4.3.1

import java.util.Date;



/**
 * UserGroup generated by hbm2java
 */

public class UserGroup  implements java.io.Serializable, java.lang.Comparable {

     private UserGroupId id;
     private Group group;
     private User user;
     private byte invited;
     private byte subscribed;
     private Date member_since;

    /**
     *
     */
    public UserGroup() {
    }

    /**
     *
     * @param id
     * @param group
     * @param user
     * @param invited
     * @param subscribed
     */
    public UserGroup(UserGroupId id, Group group, User user, byte invited, byte subscribed) {
       this.id = id;
       this.group = group;
       this.user = user;
       this.invited = invited;
       this.subscribed = subscribed;
    }
   
    /**
     *
     * @return
     */
    public UserGroupId getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(UserGroupId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Group getGroup() {
        return this.group;
    }
    
    /**
     *
     * @param group
     */
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     *
     * @return
     */
    public User getUser() {
        return this.user;
    }
    
    /**
     *
     * @param user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * @return
     */
    public byte getInvited() {
        return this.invited;
    }
    
    /**
     *
     * @param invited
     */
    public void setInvited(byte invited) {
        this.invited = invited;
    }

    /**
     *
     * @return
     */
    public byte getSubscribed() {
        return this.subscribed;
    }
    
    /**
     *
     * @param subscribed
     */
    public void setSubscribed(byte subscribed) {
        this.subscribed = subscribed;
    }

    /**
     *
     * @return
     */
    public Date getMember_since() {
        return member_since;
    }

    /**
     *
     * @param member_since
     */
    public void setMember_since(Date member_since) {
        this.member_since = member_since;
    }

    /**
     *
     * @param t
     * @return
     */
    @Override
    public int compareTo(Object t) {
        return getMember_since().compareTo(((UserGroup)t).getMember_since());
    }

}


