package com.nephtysorg.model.pojo;
// Generated 20 avr. 2015 10:17:30 by Hibernate Tools 4.3.1



/**
 * UserGroupId generated by hbm2java
 */
public class UserGroupId  implements java.io.Serializable {


     private int userId;
     private int groupId;

    public UserGroupId() {
    }

    public UserGroupId(int userId, int groupId) {
       this.userId = userId;
       this.groupId = groupId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserGroupId) ) return false;
		 UserGroupId castOther = ( UserGroupId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getGroupId()==castOther.getGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getGroupId();
         return result;
   }   


}


